# Generated by Django 3.2.9 on 2021-11-28 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_salesorder_products'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
